### ISSUE TITLE
Error when creating report

### ISSUE THREAD

**Issue by NathanCFoster** [smelly-python/smelly-python#16]
### I recently encountered this error:

```bash
Finished running pylint, creating report...
Traceback (most recent call last):
  File "/Users/nfoster/.pyenv/versions/3.8.13/bin/smelly-python", line 8, in <module>
    sys.exit(main())
  File "/Users/nfoster/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nfoster/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/nfoster/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nfoster/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/nfoster/.pyenv/versions/3.8.13/lib/python3.8/site-packages/smelly_python/command_line.py", line 67, in main
    generate_webpage(report, explanations)
  File "/Users/nfoster/.pyenv/versions/3.8.13/lib/python3.8/site-packages/smelly_python/generator/webpage_generator.py", line 155, in generate_webpage
    index.write(str(doc))
  File "/Users/nfoster/.pyenv/versions/3.8.13/lib/python3.8/site-packages/dominate/dom_tag.py", line 321, in __unicode__
    return self.render()
  File "/Users/nfoster/.pyenv/versions/3.8.13/lib/python3.8/site-packages/dominate/dom_tag.py", line 327, in render
    return u''.join(data)
TypeError: sequence item 13908: expected str instance, Tag found
```

This is from my local machine however its nearly identical to another error I've been getting while trying to setup [smell my pr](https://github.com/smelly-python/smell-my-pr). I don't know what the steps to reproduce this are as its my first time using this particular package. 

**OS: Mac Ventura 13.2.1 || Ubuntu 22.04.2 LTS
Python: 3.8.13
Smelly-Python: Latest**

Any help would be very much appreciated

**Comment by NathanCFoster** [comment]
Just got it working, would it be possible to review [this pr](https://github.com/smelly-python/smelly-python/pull/17)
